@startuml
!theme plain
hide circle
skinparam classAttributeIconSize 0
skinparam componentStyle rectangle
skinparam linetype ortho

class MarkdownView {
  - children: string
  - className?: string
  __
  + render(): JSX
}

class react-markdown {
}

class remarkGfm {
}

class remarkMath {
}

class remarkUnderline {
}

class rehypeKatex {
}

class rehypeHighlight {
}

MarkdownView -- react-markdown : utilizza
MarkdownView ..> remarkGfm : utilizza
MarkdownView ..> remarkMath : utilizza
MarkdownView ..> remarkUnderline : utilizza
MarkdownView ..> rehypeKatex : utilizza
MarkdownView ..> rehypeHighlight : utilizza

@enduml