@startuml
!theme plain
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam nodesep 45
skinparam ranksep 60
skinparam defaultFontSize 14

title Preview

top to bottom direction

class Preview {
  - currentText: string
}

class useEditorStore <<store>> {
  + currentText: string
}

class MarkdownView {
  + children: string
  + className?: string
}

Preview --> useEditorStore
Preview --> MarkdownView

@enduml
