@startuml
!theme plain
hide circle
skinparam classAttributeIconSize 0
skinparam componentStyle rectangle
skinparam linetype ortho

class Preview {
  - currentText: string
  __
  + render(): JSX
}

class useEditorStore {
  - currentText: string
  __
  + setCurrentText(text: string): void
}

class MarkdownView {
  - children: string
  - className?: string
  __
  + render(): JSX
}

Preview ..> useEditorStore : utilizza
Preview ..> MarkdownView : utilizza

@enduml